[package]
name = "distle"
version = "0.1.0"
authors = ["Karim Hajji <karim.hajji@rivm.nl>"]
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
bio = "1.5"
rayon = "1.9"

[profile.release]
lto = "fat"
codegen-units = 1
